# Generated by Django 2.1.1 on 2019-06-14 04:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='refridgerator_display_system',
            fields=[
                ('name', models.TextField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('datetime', models.DateTimeField(default=datetime.datetime(2019, 6, 14, 4, 38, 39, 701084, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='ระบบแสดงผลการใช้งาน',
        ),
    ]
