# Generated by Django 2.1.1 on 2019-06-21 17:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190614_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2019, 6, 21, 17, 46, 43, 567861, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='refridgerator_display_system',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 21, 17, 46, 43, 567861, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='refridgerator_display_system',
            name='status',
            field=models.TextField(default='OFF'),
        ),
        migrations.AddField(
            model_name='history',
            name='ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.refridgerator_display_system'),
        ),
    ]
